import { Link } from "react-router-dom";

export const columns = [
  { field: "id", headerName: "ID", minWidth: 60, maxWidth: 90 },
  {
    field: "customerName",
    headerName: "Customer Name",
    minWidth: 130,
    maxWidth: 170,
    renderCell: (params) => (
      <Link
        to={`/order/${params.row.orderNumber}`}
        style={{ textDecoration: "none", color: "unset" }}
      >
        {params.value}
      </Link>
    ),
  },
  {
    field: "status",
    headerName: "Status",
    minWidth: 100,
    maxWidth: 150,
  },
  {
    field: "totalAmount",
    headerName: "Total Amount",
    // type: "number",
    minWidth: 120,
    maxWidth: 200,
  },
  {
    field: "address",
    headerName: "Address",
    minWidth: 180,
    maxWidth: 200,
  },
];
export const rows2 = [
  {
    id: 1,
    orderNumber: "ORD-1001",
    customerName: "John Doe",
    status: "Pending",
    totalAmount: "250.00",
    address: "Cairo ",
  },
  {
    id: 2,
    orderNumber: "ORD-1002",
    customerName: "Jane Smith",
    status: "Shipped",
    totalAmount: "150.50",
    address: "Alexandria ",
  },
  {
    id: 3,
    orderNumber: "ORD-1003",
    customerName: "Alice Johnson",
    status: "Delivered",
    totalAmount: "320.75",
    address: "Giza ",
  },
  {
    id: 4,
    orderNumber: "ORD-1004",
    customerName: "Bob Brown",
    status: "Cancelled",
    totalAmount: "0.00",
    address: "Luxor ",
  },
  {
    id: 5,
    orderNumber: "ORD-1005",
    customerName: "Charlie Davis",
    status: "Pending",
    totalAmount: "450.00",
    address: "Aswan ",
  },
  {
    id: 6,
    orderNumber: "ORD-1006",
    customerName: "Diana Evans",

    status: "Shipped",
    totalAmount: "275.25",
    address: "Suez ",
  },
  {
    id: 7,
    orderNumber: "ORD-1007",
    customerName: "Ethan Harris",
    status: "Delivered",
    totalAmount: "600.00",
    address: "Port Said ",
  },
  {
    id: 8,
    orderNumber: "ORD-1008",
    customerName: "Fiona Green",
    status: "Cancelled",
    totalAmount: "0.00",
    address: "Mansoura ",
  },
  {
    id: 9,
    orderNumber: "ORD-1009",
    customerName: "George King",
    status: "Pending",
    totalAmount: "125.00",
    address: "Tanta ",
  },
  {
    id: 10,
    orderNumber: "ORD-1010",
    customerName: "Hannah Lee",
    status: "Shipped",
    totalAmount: "350.00",
    address: "Ismailia ",
  },
  {
    id: 11,
    orderNumber: "ORD-1011",
    customerName: "Ian Moore",
    status: "Delivered",
    totalAmount: "480.00",
    address: "Faiyum ",
  },
  {
    id: 12,
    orderNumber: "ORD-1012",
    customerName: "Julia Nelson",
    status: "Cancelled",
    totalAmount: "0.00",
    address: "Zagazig ",
  },
  {
    id: 13,
    orderNumber: "ORD-1013",
    customerName: "Kevin Owens",
    status: "Pending",
    totalAmount: "200.00",
    address: "Damietta ",
  },
  {
    id: 14,
    orderNumber: "ORD-1014",
    customerName: "Laura Parker",
    status: "Shipped",
    totalAmount: "300.00",
    address: "Hurghada ",
  },
  {
    id: 15,
    orderNumber: "ORD-1015",
    customerName: "Michael Quinn",
    status: "Delivered",
    totalAmount: "550.00",
    address: "Sharm El Sheikh ",
  },
  {
    id: 16,
    orderNumber: "ORD-1016",
    customerName: "Nina Roberts",
    status: "Cancelled",
    totalAmount: "0.00",
    address: "Minya ",
  },
  {
    id: 17,
    orderNumber: "ORD-1017",
    customerName: "Oliver Scott",
    status: "Pending",
    totalAmount: "175.00",
    address: "Beni Suef ",
  },
  {
    id: 18,
    orderNumber: "ORD-1018",
    customerName: "Paula Turner",
    status: "Shipped",
    totalAmount: "400.00",
    address: "Qena ",
  },
  {
    id: 19,
    orderNumber: "ORD-1019",
    customerName: "Quincy Underwood",
    status: "Delivered",
    totalAmount: "625.00",
    address: "Sohag ",
  },
  {
    id: 20,
    orderNumber: "ORD-1020",
    customerName: "Rachel Vance",
    status: "Cancelled",
    totalAmount: "0.00",
    address: "Assiut ",
  },
];


export const productColumns = [
  { field: "id", headerName: "id", minWidth: 60, maxWidth: 90 },
  {
    field: "productName",
    headerName: "Product Name",
    minWidth: 130,
    maxWidth: 170,
  },
  {
    field: "category",
    headerName: "Category",
    minWidth: 100,
    maxWidth: 150,
  },
  {
    field: "price",
    headerName: "Price",
    minWidth: 100,
    maxWidth: 150,
  },
  {
    field: "stock",
    headerName: "Stock",
    minWidth: 80,
    maxWidth: 120,
  },
];

export const productRows = [
  {
    id: 1,
    productName: "Laptop",
    category: "Electronics",
    price: "1000.00",
    stock: 50,
  },
  {
    id: 2,
    productName: "Smartphone",
    category: "Electronics",
    price: "500.00",
    stock: 100,
  },
  {
    id: 3,
    productName: "Desk Chair",
    category: "Furniture",
    price: "150.00",
    stock: 20,
  },
  {
    id: 4,
    productName: "Coffee Maker",
    category: "Appliances",
    price: "80.00",
    stock: 30,
  },
  {
    id: 5,
    productName: "Headphones",
    category: "Accessories",
    price: "60.00",
    stock: 75,
  },
  {
    id: 6,
    productName: "Tablet",
    category: "Electronics",
    price: "300.00",
    stock: 40,
  },
  {
    id: 7,
    productName: "Monitor",
    category: "Electronics",
    price: "200.00",
    stock: 25,
  },
  {
    id: 8,
    productName: "Keyboard",
    category: "Accessories",
    price: "40.00",
    stock: 150,
  },
  {
    id: 9,
    productName: "Mouse",
    category: "Accessories",
    price: "25.00",
    stock: 200,
  },
  {
    id: 10,
    productName: "Printer",
    category: "Electronics",
    price: "120.00",
    stock: 15,
  },
  {
    id: 11,
    productName: "Router",
    category: "Electronics",
    price: "70.00",
    stock: 60,
  },
  {
    id: 12,
    productName: "Webcam",
    category: "Accessories",
    price: "50.00",
    stock: 80,
  },
  {
    id: 13,
    productName: "External Hard Drive",
    category: "Storage",
    price: "100.00",
    stock: 35,
  },
  {
    id: 14,
    productName: "USB Flash Drive",
    category: "Storage",
    price: "20.00",
    stock: 300,
  },
  {
    id: 15,
    productName: "Smartwatch",
    category: "Wearables",
    price: "150.00",
    stock: 45,
  },
  {
    id: 16,
    productName: "Fitness Tracker",
    category: "Wearables",
    price: "100.00",
    stock: 50,
  },
  {
    id: 17,
    productName: "Bluetooth Speaker",
    category: "Audio",
    price: "80.00",
    stock: 70,
  },
  {
    id: 18,
    productName: "Digital Camera",
    category: "Photography",
    price: "400.00",
    stock: 10,
  },
  {
    id: 19,
    productName: "Tripod",
    category: "Photography",
    price: "30.00",
    stock: 25,
  },
  {
    id: 20,
    productName: "Projector",
    category: "Electronics",
    price: "350.00",
    stock: 5,
  },
];



